services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5601:5672"
      - "15601:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      TZ: America/Santiago
  api:
    build:
      context: ./geoviality-api
    container_name: api-container
    ports:
      - "8080:8080"
    volumes:
      - ./geoviality-api:/app
    environment:
      TZ: America/Santiago
    env_file:
      - ./geoviality-api/.env
    depends_on:
      - rabbitmq
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s
  ia:
    build:
      context: ./geoviality-ia
    container_name: ia-container
    volumes:
      - ./geoviality-ia:/app
    environment:
      TZ: America/Santiago
    env_file:
      - ./geoviality-ia/.env
    depends_on:
      - rabbitmq
      - api
      - mongo
    
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      TZ: America/Santiago
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 